"""The configurable sash inventory extracted from PostersPlus configurator.html."""
POSTERSPLUS_SASH_SLOTS = (
    ("wins", "Best Picture / Major Emmy Win"),
    ("gg_wins", "Major Golden Globe Win"),
    ("festival", "Festival Winner"),
    ("pic_noms", "Best Picture / Major Emmy Nom"),
    ("metacritic", "Metacritic Must-See"),
    ("gg_noms", "Major Golden Globe Nom"),
    ("trending", "TMDB Trending Top {{TRENDING_FETCH_COUNT}}"),
    ("trending_broad", "TMDB Trending {{TRENDING_FETCH_COUNT_PLUS_ONE}}-{{TRENDING_BROAD_FETCH_COUNT}}"),
    ("premiere", "Premiere"),
    ("new_release", "Newly Streaming (New)"),
    ("just_added", "Just Added"),
    ("new_season", "New Season"),
    ("season_finale", "Season Finale"),
    ("studio", "Notable Studio Name"),
    ("director", "Notable Director Name"),
    ("cast", "Notable Cast Name"),
    ("cult", "Cult Classic"),
    ("foreign", "Foreign Language"),
    ("true_story", "True Story"),
    ("short_film", "Short Film"),
    ("mini_series", "Miniseries"),
    ("binge_ready", "Binge Ready"),
    ("returning", "Returning"),
    ("airing", "Airing"),
    ("cancelled", "Cancelled"),
    ("ended", "Ended"),
    ("physical", "Physical"),
    ("streaming", "Streaming"),
    ("cinema", "Cinema"),
    ("production", "Production"),
)
